version = 0.1

[default]
[default.global.parameters]
stack_name = "cooklang-backend"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = [
    "AllowedOrigin=*",
    "CognitoUserPoolId=YOUR_USER_POOL_ID",
    "CognitoAppClientId=YOUR_APP_CLIENT_ID",
    "S3BucketName=cooklang-recipes-bucket"
]
